version: "3" 
services:
  site:
    command: jekyll serve -l --force_polling
    image: jekyll/jekyll
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
      - 35729:35729
  build:
    command: jekyll build
    image: jekyll/jekyll
    volumes:
      - .:/srv/jekyll